name: CI

on:
  push:
    branches:
      - 'main'
      - 'versions/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  solid-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: solid test suite
        run: bash ./test/surface/run-solid-test-suite.sh
